import Head from 'next/head';

import Header from '@/components/sections/Header';
import Footer from '@/components/sections/Footer';
import Title from '@/components/sections/Title';
import AboutUs from '@/components/sections/AboutUs';

import {
  Box,
  Grid,
  GridItem,
  VStack,
  chakra,
  Flex,
  Container,
  Button,
} from '@chakra-ui/react';

export default function Home() {
  return (
    <>
      <Head>
        <title>Roadtax Cekap | About Us</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />
      <Title title='About Us' />
      <AboutUs />

      <Box as={Container} maxW='7xl' py={6} px={10} bg='yellow.400'>
        <Grid
          templateColumns={{
            base: 'repeat(1, 1fr)',
            sm: 'repeat(2, 1fr)',
            md: 'repeat(2, 1fr)',
          }}
          gap={4}
        >
          <GridItem colSpan={1}>
            <VStack alignItems='flex-start' spacing='20px'>
              <chakra.h2 fontSize='3xl' fontWeight='700'>
                Career with Roadtax Cekap
              </chakra.h2>
              <Button colorScheme='green' size='md'>
                Join us Now
              </Button>
            </VStack>
          </GridItem>
          <GridItem>
            <Flex>
              <chakra.p>
                Making Insurance Better Together. We are looking for a new
                talent to join our teams.
              </chakra.p>
            </Flex>
          </GridItem>
        </Grid>
      </Box>

      <Footer />
    </>
  );
}
