import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";

import Header from "@/components/sections/Header";
import Footer from "@/components/sections/Footer";
import Title from "@/components/sections/Title";

const inter = Inter({ subsets: ["latin"] });

export default function ContactUs() {
  return (
    <>
      <Head>
        <title>Roadtax Cekap | Contact Us</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Title title="Contact Us" />

      <Footer />
    </>
  );
}
