import Head from 'next/head';

import Header from '@/components/sections/Header';
import Footer from '@/components/sections/Footer';
import Title from '@/components/sections/Title';

import {
  Box,
  Accordion,
  AccordionItem,
  AccordionButton,
  AccordionIcon,
  AccordionPanel,
  Center
} from '@chakra-ui/react';

const faqList = [
  {
    id: 1,
    question: 'Who can use this service?',
    answer:
      'All private-use cars and motorcycles are eligible to use this service.',
  },
  {
    id: 2,
    question: 'Is it safe to renew my roadtax online?',
    answer:
      'Yes, it is safe and secure. The online roadtax renewal through Bjak.my has been audited, verified and approved by Jabatan Pengangkutan Jalan, Bank Negara Malaysia, Persatuan Insurans Am Malaysia (PIAM) and Malaysian Takaful Association (MTA).',
  },
  {
    id: 3,
    question: 'Can I renew my roadtax if I have outstanding traffic summonses?',
    answer:
      'During the roadtax renewal process, Road Transport Department (JPJ) online service will check any outstanding summons and blacklist records at both JPJ and PDRM database systems. In order to proceed with this renewal, it is necessary for you to make payment for all your outstanding traffic offences recorded.',
  },
  {
    id: 4,
    question: 'Who can use this service?',
    answer:
      'All private-use cars and motorcycles are eligible to use this service.',
  },
  {
    id: 5,
    question: 'Is it safe to renew my roadtax online?',
    answer:
      'Yes, it is safe and secure. The online roadtax renewal through Bjak.my has been audited, verified and approved by Jabatan Pengangkutan Jalan, Bank Negara Malaysia, Persatuan Insurans Am Malaysia (PIAM) and Malaysian Takaful Association (MTA).',
  },
  {
    id: 6,
    question: 'Can I renew my roadtax if I have outstanding traffic summonses?',
    answer:
      'During the roadtax renewal process, Road Transport Department (JPJ) online service will check any outstanding summons and blacklist records at both JPJ and PDRM database systems. In order to proceed with this renewal, it is necessary for you to make payment for all your outstanding traffic offences recorded.',
  },
];

export default function Faqs() {
  return (
    <>
      <Head>
        <title>Roadtax Cekap | FAQs</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />
      <Title title='Frequently Asked Question' />

      <Box py={10} px={10}>
        <Center>
          <Accordion allowToggle>
            {faqList.map((item) => {
              return (
                <AccordionItem key={item.id} w={{ base: '100%', sm: '80%', md: '70%', lg: '70%' }}>
                  <AccordionButton>
                    <Box flex='1' textAlign='left' as='b'>
                      {item.question}
                    </Box>
                    <AccordionIcon />
                  </AccordionButton>
                  <AccordionPanel pb={4} textAlign='left'>{item.answer}</AccordionPanel>
                </AccordionItem>
              );
            })}
          </Accordion>
        </Center>
      </Box>

      <Footer />
    </>
  );
}
