import Head from 'next/head';

import Header from '@/components/sections/Header';
import Footer from '@/components/sections/Footer';
import Carousel from '@/components/sections/Carousel';
import Hero from '@/components/sections/Hero';
import Features from '@/components/sections/Features';
import Statistics from '@/components/sections/Statistics';
import Testimonial from '@/components/sections/Testimonial';

export default function Home() {
  return (
    <>
      <Head>
        <title>Roadtax Cekap | Home</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />
      <Carousel />
      <Hero />
      <Features />
      <Statistics />
      <Testimonial />
      <Footer />
    </>
  );
}
