import Head from 'next/head';

import Header from '@/components/sections/Header';
import Footer from '@/components/sections/Footer';
import Title from '@/components/sections/Title';

export default function JoinUs() {
  return (
    <>
      <Head>
        <title>Roadtax Cekap | Join Us</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />
      <Title title='Join Us' />

      <Footer />
    </>
  );
}
